# Generated by Django 3.1.5 on 2021-01-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser1',
            name='about',
        ),
        migrations.AddField(
            model_name='newuser1',
            name='account',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='newuser1',
            name='asset',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newuser1',
            name='profit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newuser1',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
