# Generated by Django 3.1.5 on 2021-01-22 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210122_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser1',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
