# Generated by Django 3.1.5 on 2021-01-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210122_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser1',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
